[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd server && npm run prisma:deploy && npm run start:prod"

[build.install]
command = "cd server && npm install --legacy-peer-deps"

[build.build]
command = "cd server && npm run prisma:generate && npm run build"
