[build]
builder = "NIXPACKS"
buildCommand = "rm -rf dist && npm run prisma:generate && npm run build"

[deploy]
startCommand = "npm run start:railway"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NPM_CONFIG_LEGACY_PEER_DEPS = "true"
