[build]
builder = "NIXPACKS"
buildCommand = "rm -rf dist node_modules/.cache && npm install --legacy-peer-deps && npm run prisma:generate && npm run build"

[deploy]
startCommand = "npm run start:railway"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NPM_CONFIG_LEGACY_PEER_DEPS = "true"
